opf/primer_view_components

.changeset/added-width-to-inputs.md
.gitignore
app/components/primer/alpha/text_field.pcss
app/forms/custom_width_fields_form.rb
lib/primer/forms/dsl/input.rb
lib/primer/forms/select.rb
lib/primer/forms/text_field.rb
previews/primer/alpha/select_preview.rb
previews/primer/alpha/text_field_preview.rb
previews/primer/forms_preview.rb
previews/primer/forms_preview/custom_width_fields_form.html.erb
test/lib/primer/forms/text_field_input_test.rb
test/lib/primer/forms_test.rb

https://community.openproject.org/wp/50740
This PR adds a new width attribute to inputs.
There are five possible values:
- `xlarge`: 96rem
- `large`: 72rem
- `medium`: 48rem
- `narrow`: 32rem
- `small`: 16rem
I chose these value arbitrarily with some looks at our specified designs. So feel free to suggest others or wait for input from design. We can change them at a later point.
The new attribute is active for:
- TextField
- Select
As I only need these right now. But it super easy to add them to other components as well.
You can use the attribute like this:
```ruby
class SingleTextFieldForm < ApplicationForm
form do |my_form|
my_form.text_field(
name: :ultimate_answer,
label: "Ultimate answer",
required: true,
caption: "The answer to life, the universe, and everything",
width: :narrow
) …
```

Added "width" attribute to inputs

---

.changeset/giant-carrots-explain.md
app/components/primer/open_project/page_header.html.erb
app/components/primer/open_project/page_header.pcss
app/components/primer/open_project/page_header.rb
previews/primer/open_project/page_header_preview.rb
previews/primer/open_project/page_header_preview/context_bar_actions.html.erb
previews/primer/open_project/page_header_preview/playground.html.erb
test/components/primer/open_project/page_header_test.rb

- Relevant WP [OP#51013](https://community.openproject.org/wp/51013)
This PR extends page header with parent link, context bar actions and responsiveness.
no
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe …

feat[#51013]: Extend page header with parent link, context bar actions and responsiveness

---

.changeset/textfield-max-width.md
app/components/primer/alpha/text_field.pcss

This PR changes the `width` CSS attribute of text input wraps to `max-width` to support a wider experience for smaller mobile views.

Changed width to max-width for text field style

---

.changeset/strong-lamps-yawn.md
app/components/primer/beta/border_box.rb
previews/primer/beta/border_box_preview.rb
test/components/beta/border_box_test.rb

In order to perform turbo stream append and prepend actions on a `BorderBox` component, we need a way to specify a target via an `id` (or some unique CSS selector). We can't guarantee there is a unique selector for the specific BorderBox's `ul` element we want to append to without an id.
This commit allows providing the `id` that will be rendered in the `BorderBox`'s ul element via the `list_id` system argument.
A system argument has been added to the "Playground" preview for the `BorderBox`.
No
https://community.openproject.org/wp/51277

Allow setting an `id` attribute on the BorderBox's `ul` element

---

previews/primer/forms_preview/custom_width_fields_form.html.erb

The FormComponent is shown in the Assets tab, but that is not easy to discover, so I added a comment

Make custom width preview easier to discover

---

.changeset/few-teachers-pull.md
app/components/primer/open_project/page_header.html.erb
app/components/primer/open_project/page_header.pcss
app/components/primer/open_project/page_header.rb
app/components/primer/open_project/page_header_element.ts
app/components/primer/open_project/zen_mode_button.html.erb
app/components/primer/open_project/zen_mode_button.rb
previews/primer/open_project/page_header_preview.rb
static/classes.json
static/constants.json
test/components/primer/open_project/page_header_test.rb
test/css/component_specific_selectors_test.rb

If a PageHeader has only a single action, it should not collapse into a menu on mobile, but stay visible in the context area with smaller size. Before, this was done via a catalyst controller. The `connectedCallback` of the controller however sometimes fires too early, resultig in the button not shrinking correctly. 
So instead, a mobile alternative is preserved for each button. That alternative has the correct `size` attrbute already set and is only rendered in the context bar when there is a single action.
see: https://community.openproject.org/projects/openproject/work_packages/54357#activity-7

Single action buttons should shrink on mobile in Primer::OpenProject::PageHeader

---

.changeset/happy-numbers-attend.md
app/components/primer/open_project/page_header.html.erb
app/components/primer/open_project/page_header.pcss
app/components/primer/open_project/page_header.rb
previews/primer/open_project/page_header_preview.rb
previews/primer/open_project/page_header_preview/playground.html.erb
static/classes.json
test/components/primer/open_project/page_header_test.rb

https://community.openproject.org/work_packages/55190
- Adds TabNav slot to PageHeader
- Removes PageHeader bottom border when TabNave is rendered

[#55190] Extend primer component PageHeader to support Tabs

---

.changeset/fifty-roses-bake.md
app/components/primer/open_project/sub_header.html.erb
app/components/primer/open_project/sub_header.pcss
app/components/primer/open_project/sub_header.rb

Fix spacings for SubHeader when filter_input or bottom pane are not present

Fix spacings for OpenProject::SubHeader

---

.changeset/cool-lions-jog.md
app/components/primer/open_project/page_header.pcss
app/components/primer/open_project/page_header.rb
static/classes.json
test/components/primer/open_project/page_header_test.rb

https://community.openproject.org/work_packages/55190
Fix Tab Nav vertical spacing in Page Header when deployed
Before:
After:

[#55190] Fix Tab Nav vertical spacing in Page Header

---

.changeset/many-pumpkins-rest.md
app/components/primer/open_project/page_header.html.erb
app/components/primer/open_project/page_header.rb
previews/primer/open_project/page_header_preview.rb
test/components/primer/open_project/page_header_test.rb

_Authors: Please fill out this form carefully and completely._
_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._
Allow rendering a SegmentedControl as part of the PageHeader, that will always be present even on mobile
https://community.openproject.org/work_packages/55639
- **No new axe scan violation** - This change does not introduce any new [axe …

Allow PageHeader to receive SegmentedControl action

---

.changeset/sweet-jars-matter.md
app/components/primer/open_project/input_group.html.erb

https://community.openproject.org/wp/51376
There is no longer adequate spacing between the caption and input group. The flex containers seem squashed together Let's use the simpler option
Follows https://github.com/opf/primer_view_components/pull/71
_Before_
_After_
https://community.openproject.org/wp/51376
There is no longer adequate spacing between the caption and input group. The flex containers seem squashed together
Let's use the simpler option

chore[Op#51376]: remove wrapping flex container that is causing caption and input group to be squeezed together

---

.changeset/calm-ravens-lay.md
app/components/primer/open_project/sub_header.pcss
app/components/primer/open_project/sub_header_element.ts
static/classes.json
test/css/component_specific_selectors_test.rb

Expand the bottomPane to full width also when the search is expanded on mobile
**Before**
**after**
Closes https://community.openproject.org/projects/openproject/work_packages/57542/activity

[57542] Project list: Filter area shrinks when search bar is opened on mobile

---

.changeset/happy-seas-leave.md
app/components/primer/open_project/page_header.pcss

https://community.openproject.org/projects/openproject/work_packages/58128/activity
With primer primitives v9 `--space-xlarge` was outdated. It [was suggested](https://github.com/primer/primitives/pull/956/files#diff-975072a9730b4c5165cbf0a7ec49966c9fb69abb0feaeeddbabc3bd0ab4a1e46L61) to use `--base-size-16` instead.

Replace outdated variable

---

.changeset/light-pots-occur.md
app/components/primer/open_project/page_header.rb
previews/primer/open_project/page_header_preview.rb
test/components/primer/open_project/page_header_test.rb

Remove support for anchor strings in PageHeader breadcrumbs as it caused problems when the name contained anchors
https://community.openproject.org/projects/openproject/work_packages/57333/activity

[57333] 500 error when opening a cost type with HTML in its name

---

.changeset/gentle-grapes-help.md
app/components/primer/open_project/page_header.html.erb
app/components/primer/open_project/page_header.pcss
static/classes.json
test/components/primer/open_project/page_header_test.rb

Avoid overlapping tabs in PageHeader tabNav when the names of the tabs are long
https://community.openproject.org/projects/openproject/work_packages/58106/activity

[58106] User tab headers overlap when header text is long

---

.changeset/three-cooks-ring.md
app/components/primer/open_project/zen_mode_button.ts

Add an event to this button while clicking on it. 
We should listen to this event, then we can add or remove zen-mode class on body element.
Closes https://community.openproject.org/projects/openproject/work_packages/58256/activity
Add a click event for button, then in core we will listen to this event and show or hide the header and sidebar by adding or removing zen-mode class on body element.

[58256] header and sidebar menu should be hidden while pressing zen mode button 

---

docs/contributors/setup.md

Keeping documentation accurate and up-to-date.
n/a
n/a
Adds a missing step to the "How to run" instructions.
n/a
n/a
n/a

Add missing step to "How to run" instructions

---

demo/Gemfile.lock

Running `bundle install` on macOS Sequoia 15.1.1 will add an entry for `arm64-darwin-24`.
It is annoying having a dirty working copy while trying to work on actual features.
n/a
n/a
n/a
n/a
n/a
n/a

Commit generated Gemfile.lock

---

app/components/primer/open_project/danger_confirmation_dialog.rb
app/components/primer/open_project/feedback_dialog.rb
static/arguments.json
static/info_arch.json

⚠️ ~~**WARNING: includes commits from #224. Please review, merge that PR first.**~~
Improve the accuracy of the documentation.
Groundwork for `DangerConfirmationDialog` documentation.
https://community.openproject.org/wp/60358
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/re …

`FeedbackDialog` and `DangerConfirmationDialog` yardoc improvements

---

.changeset/itchy-lions-count.md
app/components/primer/open_project/danger_confirmation_dialog.html.erb
app/components/primer/open_project/danger_confirmation_dialog.rb
previews/primer/open_project/danger_confirmation_dialog_preview.rb
previews/primer/open_project/danger_confirmation_dialog_preview/playground.html.erb

Allow custom texts for Cancel and Confirm buttons in DangerConfirmationDialog

Custom texts for Buttons in DangerConfirmationDialog

---

.changeset/young-doors-explode.md
previews/primer/open_project/danger_confirmation_dialog_preview.rb
previews/primer/open_project/danger_confirmation_dialog_preview/with_form_builder_form_test.html.erb
previews/primer/open_project/danger_confirmation_dialog_preview/with_form_test.html.erb
test/system/open_project/danger_confirmation_dialog_test.rb

Providing a string instead of a real path. Otherwise it will not work in the production lookbook.
https://community.openproject.org/projects/openproject/work_packages/60890/activity

Fix the dangerDialog form previews

---

.changeset/gold-moles-beg.md
app/components/primer/open_project/danger_dialog.rb
previews/primer/open_project/danger_dialog_preview/playground.html.erb
test/components/primer/open_project/danger_dialog_test.rb
test/system/open_project/danger_dialog_test.rb

Fixes a regression in 0.53.0 where callers are unable to set custom button text for the Danger Dialog.
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe why the violation cannot be resolved below.

Fix Danger Dialog regression: unable to set custom button text

---

.changeset/nasty-oranges-end.md
.changeset/polite-toys-tap.md
app/components/primer/open_project/danger_dialog.rb
app/components/primer/open_project/feedback_dialog.rb
previews/primer/open_project/danger_dialog_preview/with_additional_details.html.erb
previews/primer/open_project/feedback_dialog_preview/playground.html.erb
previews/primer/open_project/feedback_dialog_preview/with_additional_details.html.erb
previews/primer/open_project/feedback_dialog_preview/with_custom_footer.html.erb
static/arguments.json
static/info_arch.json
test/components/component_test.rb
test/components/primer/open_project/danger_dialog_test.rb
test/components/primer/open_project/feedback_dialog_test.rb

Makes title param required for **DangerDialog** and **FeedbackDialog**: Axe will raise accessibility violations in the absence of a title. We want to ensure best a11y practice, so this change makes it a required param and documents it.
This is a BREAKING change.
Fixes Axe scan violations if a title is not specified for a preview:
```
IntegrationOpenProjectDangerDialogTest#test_playground_custom_button_text [test/system/open_project/danger_dialog_test.rb:42]:
Found 1 accessibility violations:
1) empty-heading: Ensures headings have discernible text (minor) …
```

Make title param required for DangerDialog and FeedbackDialog

---

.changeset/gold-clouds-explain.md
.playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/default/aria-snapshot--after-interaction.yml
.playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/with_confirmation_check_box/aria-snapshot--after-interaction.yml
app/components/primer/open_project/danger_dialog.rb
app/components/primer/open_project/danger_dialog_form_helper.ts
test/components/primer/open_project/danger_dialog_test.rb

Improve semantics for users of assistive technology.
No visual changes
No.
https://community.openproject.org/wp/61630
Danger dialogs (both the confirmation and default, warning variant) clearly adhere to the alert dialog pattern:
> The alertdialog role is to be used on modal alert dialogs that
> interrupt a user's workflow to communicate an important message and
> require a response.
See: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role
N/A

[#61630] Danger Dialog should use `alertdialog` ARIA role

---

.changeset/soft-pots-return.md
app/components/primer/open_project/danger_dialog_form_helper.ts

⚠️ **See #244 for system tests for this bugfix**
Fix Danger Dialog scroll behaviour when the dialog contains a form.
<details><summary>Note on using Form Builders</summary>
<p>
N.B. this issue only occurs when the `form` element is rendered inside the dialog, which in turn only happens when an `action` rather than `builder` is passed as `form_arguments`.
https://qa.openproject-edge.com/lookbook/inspect/primer/open_project/danger_dialog/with_form (incorrect scroll behaviour)
https://qa.openproject-edge.com/lookbook/inspect/primer/open_project/danger_dialog/with_form_builder_form (behaves as expected)
</p>
</details> 
**Before**
**After**
No changes necessary.
https://community.openproject.org/wp/61546
This PR also applies `display: contents` to the `form` element when present.
See commit …

[#61546] Fix DangerDialog scroll behaviour w/form

---

.changeset/polite-pets-shop.md
.changeset/twelve-bags-dance.md
app/components/primer/open_project/danger_dialog.rb
app/components/primer/open_project/feedback_dialog.rb
test/components/primer/open_project/danger_dialog_test.rb
test/components/primer/open_project/feedback_dialog_test.rb

Fix broken ARIA `describedby` attribute value for the Danger and Feedback Dialogs.
**Before**
**After**
N/A
https://community.openproject.org/wp/61347
- **New axe violation** - This change introduces a new [axe scan](https://thehub.github.com/epd/engineering/dev-practicals/frontend/accessibility/readiness-routine/development/#axe-scans) violation. Please describe why the …

[#61347] Danger and Feedback Dialogs have broken ARIA describedby attribute value

---

.changeset/strong-months-carry.md
app/components/primer/open_project/side_panel/section.rb
previews/primer/open_project/side_panel_preview.rb
previews/primer/open_project/side_panel_preview/with_action_menu.html.erb
test/components/primer/open_project/side_panel_test.rb

https://community.openproject.org/work_packages/61788
Allow ActionMenu as sidepanel section action

Allow ActionMenu as sidepanel section action

---

.changeset/no-close-dialog-with-form.md
app/components/primer/dialog_helper.ts
test/system/alpha/dialog_test.rb

Do not close dialog when clicking on the backdrop when it contains a form
Closes 
https://community.openproject.org/work_packages/62076
https://community.openproject.org/work_packages/62041
Cherry-pick from upstream

Dialogs close when moving mouse outside of it

---

.changeset/spotty-islands-battle.md
app/components/primer/open_project/border_box/collapsible_header.ts

Move the check to the connectedCallback instead of the constructor because the Box might not be rendered before that.
This is an attempt to close https://community.openproject.org/projects/openproject/work_packages/62747/activity
Since I can't reproduce that locally, it is more an educated guess then anything else

[62747]  CollapsibleHeader example not working in Lookbook

---

.changeset/lazy-needles-float.md
app/components/primer/open_project/border_box/collapsible_header.rb
app/components/primer/open_project/border_box/collapsible_header.ts
test/components/primer/open_project/border_box/collapsible_header_test.rb

When accessing ~https://qa.openproject-edge.com/lookbook/inspect/primer/open_project/border_box/collapsible_header/playground~ https://qa.openproject-edge.com/lookbook/inspect/primer/open_project/border_box/collapsible_header/collapsed, you can see an error on the console:

Safeguard JS targets for CollapsibleHeaders

---

.changeset/eleven-cooks-attend.md
app/components/primer/alpha/select.rb
app/components/primer/alpha/text_area.rb
app/components/primer/alpha/text_field.pcss
app/components/primer/alpha/text_field.rb
app/components/primer/open_project/input_group.pcss
app/components/primer/open_project/input_group.rb
app/lib/primer/forms/dsl/input.rb
previews/primer/alpha/select_preview.rb
previews/primer/alpha/text_area_preview.rb
previews/primer/alpha/text_field_preview.rb
previews/primer/forms_preview/custom_width_fields_form.html.erb
previews/primer/open_project/input_group_preview.rb
test/css/component_specific_selectors_test.rb
test/lib/primer/forms_test.rb

* Introduce xsmall for input_width
* Change xlarge from 640 to 680

[61779] Form input: introduce a smaller input size for date/time

---

.changeset/upset-boats-smoke.md
.playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/default/aria-snapshot--after-interaction.yml
.playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/with_confirmation_check_box/aria-snapshot--after-interaction.yml
.playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/feedback_dialog/default/aria-snapshot--after-interaction.yml
app/components/primer/open_project/danger_dialog.html.erb
app/components/primer/open_project/feedback_dialog.html.erb

Provide a default I18n string for the close button in FeedbackDialog and DangerDialog
https://community.openproject.org/projects/design-system/work_packages/61631/activity

[61631] Primer Dialog close button ARIA label is not localised

---

test/system/open_project/tree_view_test.rb

This PR is designed to address a flickering (i.e. occasionally failing) `TreeView` test, as can be seen here: https://github.com/opf/primer_view_components/actions/runs/14855158207/job/41706622240
No changes necessary in production - this update affects tests only.
I added an `assert_selector` statement that waits for the async request to finish before asserting the "No items" item exists.

Fix flickering TreeView test

---

test/css/component_selector_use_test.rb

The CSS selector use test is still flickering (i.e. failing intermittently) because it's computationally intensive to process all the HTML for the `TreeView` and `FileTreeView` playground previews. This PR ignores these two previews, which should be safe to do because other previews also provide the same selector information.
No changes necessary in production - this update is test-only.

Skip CSS use test for `TreeView`'s playground preview

---

.changeset/fuzzy-ravens-speak.md
app/components/primer/open_project/page_header.rb
app/components/primer/open_project/sub_header.html.erb
app/components/primer/open_project/sub_header.pcss
app/components/primer/open_project/sub_header.rb
app/components/primer/open_project/sub_header/button.rb
app/components/primer/open_project/sub_header/button_group.rb
app/components/primer/open_project/sub_header/menu.rb
app/components/primer/open_project/sub_header/segmented_control.rb
previews/primer/open_project/page_header_preview/create_action.html.erb
previews/primer/open_project/sub_header_preview.rb
previews/primer/open_project/sub_header_preview/action_menu_buttons.html.erb
previews/primer/open_project/sub_header_preview/button_group.html.erb
previews/primer/open_project/sub_header_preview/custom_filter_button.html.erb
previews/primer/open_project/sub_header_preview/dialog_buttons.html.erb
static/classes.json
test/components/component_test.rb
test/components/primer/open_project/sub_header/button_group_test.rb
test/components/primer/open_project/sub_header/button_test.rb
test/components/primer/open_project/sub_header/menu_test.rb
test/components/primer/open_project/sub_header/segemented_control_test.rb
test/components/primer/open_project/sub_header_test.rb
test/css/component_specific_selectors_test.rb

Improve the mobile behaviour of the SubHeader by collapsing all buttons to icon-only variants. In that scope, we enforce icons on all buttons even in the desktop variant.
**ToDo**
I created SubClasses for all possible types of actions that the SubHeader can have, in order to enfore the icon to be set. The only exception are the free `filter_button_component` and `action_component` slots that currently allow anything to be rendered. There, we cannot enforce the icons. The goal is to remove those slots, but that is out of scope for now
https://community.openproject.org/projects/openproject/work_packages/60332/activity

[60332] Implement proper mobile behaviour for Sub Header component (OP Primer)

---

.changeset/upset-pets-rest.md
app/components/primer/open_project/tree_view/tree_view_sub_tree_node_element.ts

_Authors: Please fill out this form carefully and completely._
_Reviewers: By approving this Pull Request you are approving the code change, as well as its deployment and mitigation plans._
_Please read this description carefully. If you feel there is anything unclear or missing, please ask for updates._
This PR fixes a bug causing the expand/collapse arrow on sub-trees in the `TreeView` component to do nothing. An error is also visible in the Javascript console (see the linked work package for details).
No changes necessary in production environments.
https://community.openproject.org/projects/design-system/work_packages/63920/activity
The issue was caused by attempting to query the DOM in `connectedCallback`, which is generally not a good idea because the DOM may or may not be available …

[#63920] Fix issue causing TreeView sub-trees to not expand/collapse when clicking the arrows

---

.changeset/thin-jeans-help.md
app/components/primer/open_project/border_box/collapsible_header.rb
app/components/primer/open_project/collapsible_section.rb
previews/primer/open_project/border_box/collapsible_header_preview/playground.html.erb
test/components/primer/open_project/border_box/collapsible_header_test.rb
test/components/primer/open_project/collapsible_section_test.rb

Enforce title for CollapsibleSection and CollapsibleHeader to be a String
https://community.openproject.org/projects/design-system/work_packages/64149/activity

[64149] Raise an error if no string is passed to the CollapsibleSection

---

.changeset/good-snails-decide.md
.playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/aria-snapshot.yml
app/components/primer/open_project/page_header/title.rb

Set the page header tag to h2
Closes https://community.openproject.org/wp/64228

[64228] Home screen widgets have the wrong headline tag

---

.changeset/fair-cloths-guess.md
app/components/primer/open_project/sub_header/menu.rb

A vanilla `Primer::Alpha::ActionMenu` allows adding sub menus via the `sub_menu_item` slot. `Primer::OpenProject::SubHeader::Menu` wraps that original ActionMenu but as of now, does not delegate the call to add sub menus.
Adding the method call to the ones delegated to the `@menu` instance variable of a `Primer::OpenProject::SubHeader::Menu` instance.

enable sub menu in sub header action menu

---

.gitattributes
script/merge-upstream

* Removes customised merge driver for `package.json` from `.gitattributes`.
* Updates `/script/merge-upstream` to re-run `./setup` (`bundle install` `npm install`).
* Commits updated `Gemfile.lock` and `package-lock.json`.

`script/merge-upstream` workflow fixes

---

.changeset/purple-paths-look.md
app/components/primer/open_project/page_header.rb
previews/primer/open_project/page_header_preview.rb
test/components/primer/open_project/page_header_test.rb

Add option to skip breadcrumb items for mobile
No
https://community.openproject.org/wp/63777
We considered two approaches:
1. Let the caller define the mobile back button explicitly (e.g via a separate slot). This was rejected, because we for one cannot control, that whatever people enter there matches our expectations of the mobile breadcrumb. Second, the default is still that the back button is build based on the breadcrumb. We wanted to keep that behaviour.
2. We exlude individal items from being considered for the mobile link. Thus, we keeo control over the consistencies between desktop and mobile and have a solution that only affects those exceptions, where the direct parent is not the one to be chosen for the mobile link.

[63777] Add option to skip indiviual items from mobile breadcrumb behaviour

---

.changeset/hip-items-sip.md
app/components/primer/alpha/text_field.pcss
app/components/primer/open_project/page_header.pcss
previews/primer/open_project/page_header_preview.rb
previews/primer/open_project/page_header_preview/description.html.erb
test/css/component_specific_selectors_test.rb
test/system/open_project/page_header_test.rb

Add link underline effect to PageHeader descriptions
https://community.openproject.org/wp/65252

[65252] Links in descriptive text not distinguishable enough

---

.changeset/thin-teams-invent.md
app/components/primer/open_project/page_header.pcss

Avoid increasing PageHeader description
https://community.openproject.org/wp/67625

[67625] Page header tab nav is broken in combination with items page and page header description

---

.changeset/fuzzy-baboons-grow.md
app/components/primer/open_project/filterable_tree_view.html.erb
app/components/primer/open_project/filterable_tree_view.rb
previews/primer/open_project/filterable_tree_view_preview/hide_segmented_control.html.erb
previews/primer/open_project/filterable_tree_view_preview/playground.html.erb
test/components/primer/open_project/filterable_tree_view_test.rb

The preview for a hidden SegmentedControl within the FilterableTreeView was broken, because it is actually needed for the filter function. So now, instead of not rendering it at all, we simply hide it (which is consistent to the include sub-items checkbox).
Further, the wrapper around the two is only rendered conditionally, to avoid empty white space when both are hidden.
* https://community.openproject.org/wp/67727
* https://community.openproject.org/wp/67723

[67727] Preview for hidden SegementedControl in FilterableTreeView is broken

---

.changeset/spotty-sheep-dream.md
app/components/primer/open_project/filterable_tree_view.rb
app/components/primer/open_project/filterable_tree_view/sub_tree.rb
previews/primer/open_project/filterable_tree_view_preview.rb
previews/primer/open_project/filterable_tree_view_preview/form_input.html.erb
previews/primer/open_project/filterable_tree_view_preview/playground.html.erb
test/components/primer/open_project/filterable_tree_view_test.rb
test/system/open_project/filterable_tree_view_test.rb

Support `select_variant: :single` inroduced in https://github.com/opf/primer_view_components/pull/360 in FilterableTreeView
https://community.openproject.org/wp/67542
When the single select variant is chosen, the include sub-items checkbox and the SegmentedControl are hidden per default as they make no sense for that selection variant

[67542] Allow single selection variant for the FilterableTtreeView
